= Lab 13: Color Palette Generator DevLog
Pluto Zitek <https://github.com/GemedetAdept>

:description: DevLog for Lab 13 of my work on the color palette generator.
:url-repo: https://github.com/GemedetAdept/cs1400-color-palette-generator
:stem: latexmath


.Goals
****
* [ ] Implement remaining conversion methods
** [ ] HEX
*** [ ] HEX to HSL
*** [ ] HEX to HSV
*** [ ] HEX to RGB
** [ ] HSL
*** [ ] HSL to HEX
** [ ] HSV
*** [ ] HEX
** [ ] RGB
*** [ ] RGB to HEX
* [ ] Implement `ValueDeviation` class for controlled randomization of output colors
** [ ] Logistic function which can be finely tuned
** [ ] Randomization of Hue value
****

== Implementation and Progress
---

=== Scope of ValueDeviation()

Because RGB and HEX both contain three values, each with the same range stem:[(\mathit{R,G,B}) \in \mathbb{R} \text{[0,1\]}] and stem:[(\mathit{H_R,H_G,H_B}) \in \mathbb{R} \text{[0$_{10}$,1$_{10}$\]}], which are all congruent, they can be geometrically visualized as _cubes_ (Fig. 1). 

HSV and HSL, albeit also containing three values, contain two distinct ranges and value types. The hue (stem:[\mathit{H_V,H_L}]) has a different range and is measured in degrees: stem:[\mathit{H_V,H_L} \in \mathbb{R} \text{[0$^{\circ}$,360$^{\circ}$\]}]. This is distinct from the shared range and value type of saturation (stem:[\mathit{S_V,S_L}]), value (stem:[\mathit{V}]), and lightness (stem:[\mathit{L}]): stem:[\mathit{S_V,S_L} \in \mathbb{R} \text{[0,1\]}], stem:[\mathit{V} \in \mathbb{R} \text{[0,1\]}], stem:[\mathit{L} \in \mathbb{R} \text{[0,1\]}]. This combination of dislike ranges and types means that both HSV and HSL are visualized as _cylinders_ (Fig. 2). 

While stem:[\mathit{H_V}] and stem:[\mathit{H_L}] are equal, stem:[\mathit{S_V}] and stem:[\mathit{S_L}], & stem:[\mathit{V}] and stem:[\mathit{L}] are _not_. This requires four more, unique deviation methods, which will have to be individually tuned. As such, I've opted to limit the current scope and focus only on the deviation methods for the hues of HSV and HSL, and for all values of RGB and HEX. 